name: Venus Docs CI/CD

on:
  push:
    branches: 
      - main

jobs:
  blog-cicd:
    name: Build & deploy venus-docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2.3.4

    - name: Setup node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'

    - name: Cache node modules
      uses: actions/cache@v2.1.3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install

    - name: Generate files
      run: yarn build

    - name: Push to gh-pages
      env:
        GITHUB_REPO: github.com/Chinesee/venus-docs.git
      run: |
        cd ./docs/.vuepress/dist
        git init
        git config --local user.name "LeoKu"
        git config --local user.email "czc12580520@gmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" HEAD:gh-pages
